# Generated by Django 3.0.7 on 2020-06-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created',
            field=models.CharField(default='글을 생성했습니다.', max_length=100),
        ),
    ]
