# Generated by Django 3.0.7 on 2020-06-10 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='created',
        ),
    ]
